# Generated by Django 6.1 on 2026-08-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Bengaluru · Est. 2014', max_length=60)),
                ('heading_line1', models.CharField(default='Forge a body', max_length=60)),
                ('heading_line2', models.CharField(default='built to last', max_length=60)),
                ('description', models.TextField(default='A members-only strength club with elite equipment, data-driven programming and coaches who know your name. Your first session is on us.')),
                ('cta_text', models.CharField(default='Book on WhatsApp', max_length=30)),
                ('cta_link', models.CharField(default='https://wa.me/919876543210', max_length=200)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
            },
        ),
    ]
