# Generated by Django 6.1 on 2026-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, help_text='e.g. 1200, 18, 24, 4.9', max_digits=6)),
                ('suffix', models.CharField(blank=True, help_text='e.g. +, /7, ★', max_length=10)),
                ('label', models.CharField(help_text='e.g. Active Members', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Stat',
                'verbose_name_plural': 'Stats',
                'ordering': ['order'],
            },
        ),
    ]
