# Generated by Django 6.1 on 2026-08-18 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Who We Are', max_length=60)),
                ('heading', models.CharField(default='A strength club, not a treadmill warehouse', max_length=150)),
                ('description', models.TextField(default='IronForge was built by competitive lifters who were tired of crowded floors and coaches who count reps from behind a desk.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_value', models.CharField(help_text='e.g. 14,000 or 50+', max_length=20)),
                ('label', models.CharField(help_text='e.g. Sq Ft Floor', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('about_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='pages.aboutsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
