# Generated by Django 6.1 on 2026-08-18 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_aboutsection_aboutfeature_aboutstat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('icon', models.CharField(choices=[('dumbbell', 'Dumbbell'), ('heart', 'Heart Pulse'), ('users', 'Users'), ('flame', 'Flame'), ('timer', 'Timer'), ('target', 'Target'), ('trophy', 'Trophy'), ('zap', 'Zap')], default='dumbbell', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='programs/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProgramsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='What We Do', max_length=60)),
                ('heading', models.CharField(default='Programs engineered around you', max_length=150)),
            ],
            options={
                'verbose_name': 'Programs Section',
                'verbose_name_plural': 'Programs Section',
            },
        ),
        migrations.CreateModel(
            name='ProgramFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.program')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
