# Generated by Django 6.1 on 2026-08-18 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_program_programssection_programfeature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Ready To Transform?', max_length=60)),
                ('heading_before', models.CharField(default='Start your', max_length=40)),
                ('heading_highlight', models.CharField(default='Fitness', max_length=40)),
                ('heading_after', models.CharField(default='journey today', max_length=40)),
                ('subtext', models.CharField(default='Flexible memberships. No hidden fees. Cancel anytime.', max_length=150)),
                ('cta_text', models.CharField(default='Join Now', max_length=30)),
                ('cta_link', models.CharField(default='#contact', max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cta/')),
            ],
            options={
                'verbose_name': 'CTA Section',
                'verbose_name_plural': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(default='Member', max_length=40)),
                ('quote', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Member Stories', max_length=60)),
                ('heading', models.CharField(default='Real people. Real results.', max_length=150)),
            ],
            options={
                'verbose_name': 'Testimonials Section',
                'verbose_name_plural': 'Testimonials Section',
            },
        ),
        migrations.CreateModel(
            name='CTAFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('dumbbell', 'Dumbbell'), ('heart', 'Heart Pulse'), ('users', 'Users'), ('flame', 'Flame'), ('timer', 'Timer'), ('target', 'Target'), ('trophy', 'Trophy'), ('zap', 'Zap')], default='target', max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('cta_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.ctasection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
