# Generated by Django 6.1 on 2026-08-18 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_ctasection_testimonial_testimonialssection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Enquiry & Support', max_length=60)),
                ('heading', models.CharField(default='Reach us the way you prefer', max_length=150)),
                ('form_intro', models.CharField(default="Fill this in and we'll open your mail app with everything ready to send.", max_length=150)),
                ('contact_email', models.EmailField(default='hello@ironforge.fit', max_length=254)),
                ('topics', models.TextField(default='Membership enquiry\nPersonal training\nCorporate / group\nOther', help_text='One topic per line, shown in the enquiry form dropdown')),
                ('address_line', models.CharField(default='IronForge Strength Club, 12 MG Road, Bengaluru 560001', max_length=200)),
                ('opening_hours', models.CharField(default='Mon-Sat 5:00-23:00 · Sun 6:00-14:00', max_length=150)),
                ('maps_query', models.CharField(default='IronForge Strength Club, 12 MG Road, Bengaluru 560001', help_text='Address used to build the embedded map and directions link', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Section',
                'verbose_name_plural': 'Contact Section',
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.PositiveIntegerField(help_text='In rupees, e.g. 2400')),
                ('period', models.CharField(default='/month', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge_text', models.CharField(blank=True, default='Most Popular', max_length=30)),
                ('cta_text', models.CharField(default='Enquire now', max_length=30)),
                ('cta_link', models.CharField(default='#contact', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='Membership', max_length=60)),
                ('heading', models.CharField(default='Simple tiers, no lock-in', max_length=150)),
            ],
            options={
                'verbose_name': 'Pricing Section',
                'verbose_name_plural': 'Pricing Section',
            },
        ),
        migrations.CreateModel(
            name='ContactMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('phone', 'Phone'), ('chat', 'Chat'), ('email', 'Email')], default='phone', max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('subtitle', models.CharField(max_length=100)),
                ('link_text', models.CharField(max_length=40)),
                ('link_href', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contact_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='methods', to='pages.contactsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='pages.pricingplan')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
