# Generated by Django 6.1 on 2026-08-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_contactsection_pricingplan_pricingsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagline', models.CharField(default='Stronger Everyday', max_length=60)),
                ('description', models.CharField(default="IronForge is more than a gym. It's a community built on discipline, dedication and relentless progress.", max_length=200)),
                ('copyright_text', models.CharField(default='© 2026 IronForge Fitness. All rights reserved.', max_length=100)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('role', models.CharField(help_text='e.g. Head Strength Coach', max_length=60)),
                ('credentials', models.CharField(help_text='e.g. NSCA-CSCS · 11 yrs · Powerlifting', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainers/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrainersSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow_text', models.CharField(default='The Team', max_length=60)),
                ('heading', models.CharField(default='Coaches who know your name', max_length=150)),
            ],
            options={
                'verbose_name': 'Trainers Section',
                'verbose_name_plural': 'Trainers Section',
            },
        ),
        migrations.CreateModel(
            name='FooterQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_links', to='pages.footersection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLegalLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40)),
                ('link', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_links', to='pages.footersection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X'), ('threads', 'Threads')], max_length=20)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('footer_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='pages.footersection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
