# Generated by Django 6.1 on 2026-08-18 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='dark', max_length=5)),
                ('logo_text_primary', models.CharField(default='IRON', max_length=30)),
                ('logo_text_secondary', models.CharField(default='FORGE', max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('cta_text', models.CharField(default='Free Trial', max_length=30)),
                ('cta_link', models.CharField(default='#contact', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30)),
                ('link', models.CharField(help_text='e.g. #about or /programs', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nav_links', to='sitesettings.sitesettings')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
