# Generated by Django 6.1 on 2026-08-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_link',
            field=models.CharField(blank=True, default='https://wa.me/919876543210', max_length=200),
        ),
    ]
